version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-alopecia
    ports:
      - "5000:5000"
    volumes:
      - ./src/artifacts:/mlflow/artifacts
      - ./src/mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db

    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow/artifacts
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts

