name: alopecia
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.17=py312ha1a9051_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=3_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.3=py312he06e257_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.74.0
      - docker==7.1.0
      - easygui==0.98.3
      - fastapi==0.124.4
      - filelock==3.19.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fonttools==4.61.1
      - fsspec==2025.9.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - huey==2.5.5
      - idna==3.11
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.12.0
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - libclang==18.1.1
      - lz4==4.4.5
      - mako==1.3.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mlflow==3.7.0
      - mlflow-skinny==3.7.0
      - mlflow-tracing==3.7.0
      - mpmath==1.3.0
      - mtcnn==1.0.0
      - namex==0.1.0
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - smmap==5.0.2
      - sqlalchemy==2.0.45
      - sqlparse==0.5.4
      - starlette==0.50.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - torch==2.7.0+cu126
      - torchvision==0.22.0+cu126
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - waitress==3.0.2
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: C:\Users\rubi6\anaconda3\envs\alopecia
